# Generated by Django 5.1.6 on 2025-03-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='exercise_images/')),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='exercise_videos/')),
            ],
        ),
    ]
