# Generated by Django 5.1.6 on 2025-03-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_remove_question_test_remove_test_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
