# Generated by Django 5.1.6 on 2025-03-22 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_question_answer_test_resulttest_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255),
        ),
    ]
