# Generated by Django 5.1.6 on 2025-03-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_test_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
    ]
