# Generated by Django 5.1.6 on 2025-03-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_test_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
