# Generated by Django 5.1.6 on 2025-03-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_article_author_alter_exercise_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(default=None, upload_to='test_images/'),
        ),
    ]
