# Generated by Django 5.1.6 on 2025-04-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Чоловіча'), ('F', 'Жіноча'), ('O', 'Інша')], max_length=1, null=True, verbose_name='Стать'),
        ),
    ]
