# Generated by Django 5.1.6 on 2025-04-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_birth_date_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='video',
        ),
        migrations.AddField(
            model_name='exercise',
            name='breathing_pattern',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
