# Generated by Django 5.1.6 on 2025-04-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_exercise_video_exercise_breathing_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
    ]
