# Generated by Django 5.1.6 on 2025-04-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_exercise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
