# Generated by Django 5.1.6 on 2025-04-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_exercise_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='emoji',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
