# Generated by Django 5.1.6 on 2025-04-22 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_exercise_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sex_rec',
            field=models.CharField(blank=True, choices=[('M', 'Чоловіча'), ('F', 'Жіноча'), ('A', 'Всі')], max_length=1, null=True, verbose_name='Рекомендовано для певної статі'),
        ),
        migrations.CreateModel(
            name='ResultTestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.CharField(blank=True, max_length=255)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_user', to='api.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
