# Generated by Django 5.1.6 on 2025-04-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_article_sex_rec_resulttestuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(default='exercise_images/default.png', upload_to='exercise_images/'),
        ),
    ]
