# Generated by Django 5.1.6 on 2025-04-28 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttestuser',
            name='passed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
