# Generated by Django 5.1.6 on 2025-05-08 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_articles', models.ManyToManyField(blank=True, to='api.article')),
                ('saved_exercises', models.ManyToManyField(blank=True, to='api.exercise')),
                ('saved_tests', models.ManyToManyField(blank=True, to='api.test')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
